- platform: template
  sensors:
    bathroom_motion:
      friendly_name: "Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('binary_sensor.bathroom_sensor_motion', 'on') }}"

- platform: template
  sensors:
    office_motion:
      friendly_name: "Office Motion"
      device_class: motion
      value_template: "{{ is_state('binary_sensor.office_motion_sensor_motion', 'on') }}"

#  - platform: huesensor

- platform: template
  sensors:
    office_unoccupied:
      friendly_name: "Office Unoccupied"
      delay_off:
        minutes: 5
      value_template: >-
        {{ is_state('binary_sensor.office_motion', 'off')
          and not is_state('sensor.sean_room_location', 'office')
          and not is_state('sensor.emily_room_location', 'office')
          and is_state('input_boolean.office_occupied', 'off')
          and not is_state('sensor.steam_76561197976250572', 'online') }}

- platform: template
  sensors:
    living_room_unoccupied:
      friendly_name: "Living Room Unoccupied"
      delay_off:
        minutes: 5
      value_template: >-
        {{ is_state('binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_2', 'off')
          and is_state('binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone', 'off')
          and is_state('binary_sensor.humen_sensor_1m_91d78c_presence', 'clear')
          and is_state('binary_sensor.humen_sensor_1m_91d9f0_presence', 'clear')
          and not is_state('sensor.sean_room_location', 'living_room')
          and not is_state('sensor.emily_room_location', 'living_room')
          and not is_state('sensor.joyce_room_location', 'living_room')
          and not is_state('media_player.plex_living_room_tv', 'paused')
          and not is_state('media_player.plex_living_room_tv', 'playing')
          and not is_state('media_player.sony_xbr_65x900h', 'playing')
          and is_state('input_boolean.living_room_occupied', 'off') }}

- platform: template
  sensors:
    bedroom_unoccupied:
      friendly_name: "Bedroom Unoccupied"
      delay_off:
        minutes: 5
      value_template: >-
        {{ is_state('binary_sensor.bedroom_sensor_motion', 'off')
          and not is_state('sensor.sean_room_location', 'bedrooom')
          and not is_state('sensor.emily_room_location', 'bedroom')
          and not is_state('media_player.bedroom_tv', 'paused')
          and not is_state('media_player.bedroom_tv', 'playing')
          and not is_state('media_player.bedroom_speaker', 'playing')
          and is_state('input_boolean.bedtime_emily', 'off')
          and is_state('input_boolean.bedroom_occupied', 'off')
          and is_state('input_boolean.bedtime_sean', 'off') }}



- platform: template
  sensors:
    upstairs_actively_cooling:
      friendly_name: "Upstairs Actively Cooling"
      unique_id: upstairs_actively_cooling
      device_class: running
      value_template: >
        {{ state_attr('climate.upstairs', 'hvac_action') == 'cooling' }}

    downstairs_actively_cooling:
      friendly_name: "Downstairs Actively Cooling"
      unique_id: downstairs_actively_cooling
      device_class: running
      value_template: >
        {{ state_attr('climate.downstairs', 'hvac_action') == 'cooling' }}

    upstairs_actively_heating:
      friendly_name: "Upstairs Actively Heating"
      unique_id: upstairs_actively_heating
      device_class: running
      value_template: >
        {{ state_attr('climate.upstairs', 'hvac_action') == 'heating' }}

    downstairs_actively_heating:
      friendly_name: "Downstairs Actively Heating"
      unique_id: downstairs_actively_heating
      device_class: running
      value_template: >
        {{ state_attr('climate.downstairs', 'hvac_action') == 'heating' }}

