default_view:
  name: Home
  view: yes
  icon: mdi:home
  entities:
    - group.family
    - group.lights
    - group.indoors
    - group.weather_one
    - group.weather_two

### FAMILY ###
family:
  name: Family
  view: no
  entities:
    - group.sean
    - sensor.sean_room_status
    - group.emily
    - sensor.emily_room_status
    - sensor.work_commute

sean:
  name: Sean
  view: no
  entities:
    - device_tracker.sean_phone #Phone
    - device_tracker.sean_bt_bedroom
    - device_tracker.sean_bt_living_room
    - device_tracker.sean_bt_office

emily:
  name: Emily
  view: no
  entities:
    - device_tracker.emily_phone #Phone
    - device_tracker.emily_bt_bedroom
    - device_tracker.emily_bt_living_room
    - device_tracker.emily_bt_office


gtracker:
  name: Google Tracker
  view: no
  entities:
    - !secret gtracker_one
    - !secret gtracker_two

### OVERVIEW ###
lights:
  name: Overview
  control: hidden
  entities:
    - light.living_room
    - light.bedroom
    - light.bathroom
    - light.office
    - vacuum.rosie
    - sensor.plex
#    - sensor.usps_mail
#    - sensor.usps_packages
#    - camera.usps_mail

### CLIMATE ###
indoors:
  name: Indoor Climate
  view: no
  entities:
    - climate.living_room
    - sensor.living_room_thermostat_hvac_state
    - sensor.living_room_thermostat_humidity
    - sensor.temperature_158d0002478a21
    - sensor.bathroom_temperature_f
    - sensor.office_temperature_f

weather_one:
  name: Weather Forecast
  view: no
  entities:
    - weather.dark_sky

weather_two:
  name: Weather Details
  view: no
  entities:
    - sensor.sun_elevation
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_nearest_storm_distance
    - sensor.dark_sky_precip_probability

### ROOMS ###
# LIVING ROOM
livingroom:
  name: Living Room
  view: yes
  icon: mdi:sofa
  entities:
    - group.livingroom_full
    - group.neato

livingroom_full:
  name: Living Room Lights
  view: no
  entities:
    - light.lr1
    - light.lr2
    - switch.outside_lights
    - binary_sensor.door_window_sensor_158d00023eb0bb
    - binary_sensor.motion_sensor_158d0002047afe
    - sensor.illumination_158d0002047afe
    - media_player.plex_living_room_tv

# BEDROOM
bedroom:
  name: Bedroom
  view: yes
  icon: mdi:hotel
  entities:
    - group.bedroom_lights_full
    - group.bathroom_lights
    - group.bedroom_full
    - media_player.bedroom_tv
    - media_player.bedroom_speaker

bedroom_full:
  name: Bedroom
  view: no
  entities:
    - binary_sensor.motion_sensor_158d000237a64a
    - sensor.temperature_158d0002478a21
    - sensor.humidity_158d0002478a21
    - sensor.illumination_158d000237a64a
    - sensor.bathroom_motion_sensor
    - sensor.bathroom_temperature_f
    - sensor.bathroom_battery

bedroom_lights_full:
  name: Bedroom Lights
  view: no
  entities:
    - light.br1
    - light.br2

bathroom_lights:
  name: Bathroom Lights
  view: no
  entities:
    - light.ba1
    - light.ba2
    - light.ba3
    - light.ba4

bedroom_media:
  name: Bedroom Media
  view: no
  entities:
    - light.br1
    - light.br2

# OFFICE
office:
  name: Office
  view: yes
  icon: mdi:keyboard
  entities:
    - group.office_lights_full
    - group.office_full

office_lights_full:
  name: Office Lights
  view: no
  entities:
    - light.of1
    - light.of2
    - scene.office_normal_lighting

office_full:
  name: Office
  view: no
  entities:
    - switch.office_fan
    - switch.smart_plug_one
    - sensor.office_temperature_f
    - sensor.office_motion_motion_sensor
    - sensor.office_battery
    - sensor.office_lux
    - sensor.laptop_socket

### LIGHTS ###
bedtime_lights:
  name: Bedtime Lights
  view: no
  entities:
    - light.bedroom
    - light.office
    - light.living_room
    - light.bathroom

### SETTINGS ###
settings:
  view: yes
  name: Settings
  icon: mdi:settings
  entities:
    - group.monitor
    - group.pihole
    - group.qbit
    - group.speedtest
    - group.rssi
    - group.input

neato:
  view: no
  name: Neato Vacuum
  icon: mdi:broom
  entities:
    - vacuum.rosie
    - camera.rosie_cleaning_map

monitor:
  view: no
  name: System
  icon: mdi:settings
  entities:
    - sensor.processor_use
    - sensor.disk_use_percent_home
    - sensor.memory_use_percent
#    - sensor.ipv4_address_eth0
#    - sensor.network_in_eth0
#    - sensor.network_out_eth0
    - sensor.last_boot

pihole:
  view: no
  name: Pi-Hole
  entities:
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_queries_today
    - sensor.pihole_dns_unique_clients
    - sensor.pihole_dns_unique_domains
    - sensor.pihole_domains_blocked

qbit:
  view: no
  name: qBittorrent
  entities:
    - sensor.qbittorrent_status
    - sensor.qbittorrent_down_speed
    - sensor.qbittorrent_up_speed

speedtest:
  view: no
  name: Internet Speed
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload

rssi:
  view: no
  name: BT RSSI
  entities:
    - sensor.bedroom_sean_gh_rssi
    - sensor.livingroom_sean_gh_rssi
    - sensor.office_sean_gh_rssi
    - sensor.bedroom_emily_gh_rssi
    - sensor.livingroom_emily_gh_rssi
    - sensor.office_emily_gh_rssi

### Input Booleans ###
input:
  view: no
  name: Input Booleans
  icon: mdi:toggle_switch
  entities:
    - input_boolean.bedtime_sean
    - input_boolean.bedtime_emily
    - input_boolean.sean_bedroom_presence
    - input_boolean.sean_living_room_presence
    - input_boolean.sean_office_presence
    - input_boolean.emily_bedroom_presence
    - input_boolean.emily_living_room_presence
    - input_boolean.emily_office_presence

### AUTOMATIONS ###
auto:
  view: yes
  name: Automations
  icon: mdi:creation
  entities:
    - group.automation
    - group.presence
    - group.livingroom_auto
    - group.bedroom_auto
    - group.bedtime_auto
    - group.office_auto
    - group.automedia
    - group.scene

bedtime_auto:
  view: no
  name: Bedtime Automations
  entities:
    - automation.bedtime
    - automation.bedtime_emily
    - automation.morning
    - automation.morning_emily
    - automation.rain_sounds
    - automation.rain_sounds_off

office_auto:
  view: no
  name: Office Automations
  entities:
    - automation.office_auto_brightness
    - automation.office_auto_brightness_transition
    - automation.turn_on_fan_above_certain_temp
    - automation.turn_off_fan_below_certain_temp
    - automation.turn_off_office_fan_without_motion
    - automation.turn_off_office_lights_above_lux
    - automation.turn_office_lights_without_motion_one_min

livingroom_auto:
  view: no
  name: Living Room Automations
  entities:
    - automation.living_room_auto_brightness
    - automation.living_room_auto_brightness_transition
    - automation.living_room_lights_off_no_motion
    - automation.turn_off_living_room_lights_above_lux
    - automation.door_closed_turn_on_nest
    - automation.door_open_turn_off_nest

bedroom_auto:
  view: no
  name: Bedroom Automations
  entities:
    - automation.bedroom_auto_brightness
    - automation.bedroom_auto_brightness_transition
    - automation.bedroom_lights_off_no_motion
    - automation.bathroom_lights_on_motion
    - automation.bathroom_lights_on_motion_bedtime
    - automation.bathroom_lights_on_motion_early_morning
    - automation.bathroom_lights_off_no_motion
    - automation.bathroom_lights_off_no_motion_night
    - automation.showering
    - automation.not_showering

automation:
  view: no
  name: Home Automations
  entities:
    - automation.away_mode
    - automation.lights_on_in_the_evening
    - automation.nest_normal_mode
    - automation.nest_normal_mode_google_tracker
    - automation.voice_sean_is_home
    - automation.voice_emily_is_home
    - automation.morning_alarm_lights
    - automation.turn_on_air_fresh
    - automation.outside_lights_on_at_sunset
    - automation.outside_lights_off_at_ten

presence:
  view: no
  name: Room Presence
  entities:
    - automation.sean_in_bedroom
    - automation.sean_in_living_room
    - automation.sean_in_office
    - automation.sean_is_away
    - automation.emily_in_bedroom
    - automation.emily_in_living_room
    - automation.emily_in_office
    - automation.emily_is_away

automedia:
  view: no
  name: Media Automations
  entities:
    - automation.media_player_playing
    - automation.media_player_stopped
    - automation.media_player_paused
    - automation.media_player_unpaused
    - automation.media_player_pause_to_idle
    - automation.bedroom_player_playing
    - automation.bedroom_player_stopped
    - automation.bedroom_player_paused
    - automation.bedroom_player_unpaused
    - automation.bedroom_player_pause_to_idle
