# Bathroom Lights on with Motion
- alias: Bathroom Lights on motion
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '07:00:01'
        before: '21:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'

# Bathroom Lights on with Motion at Bedtime
- alias: Bathroom Lights on motion bedtime
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '21:00:01'
        before: '04:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.cl1
        brightness_pct: '25'
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.cl1
        brightness_pct: '25'

# Bathroom Lights on with Motion at Early Morning
- alias: Bathroom Lights on motion early morning
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: light.bathroom
        state: 'off'
      - condition: time
        after: '04:30:01'
        before: '07:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
        transition: 60
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
        transition: 60

# Bathroom Lights off without Motion night
- alias: Bathroom Lights off no motion night
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'off'
    for:
      seconds: 90
  condition:
    - condition: time
      after: '21:00:01'
      before: '04:20:00'
    - condition: state
      entity_id: binary_sensor.bathroom_sensor_motion
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2

# Bathroom Lights off without Motion
- alias: Bathroom Lights off no motion
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_sensor_motion
    to: 'off'
    for:
      minutes: 6
  condition:
    - condition: time
      after: '04:20:01'
      before: '21:00:00'
    - condition: state
      entity_id: binary_sensor.bathroom_sensor_motion
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2

# Turn on air fresh for ten minutes each hour when home
- alias: Turn on air fresh
  initial_state: 'on'
  trigger:
    platform: time_pattern
    hours: '/1'
    minutes: '00'
    seconds: '00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '06:00:00'
        before: '22:15:00'
  action:
    - service: switch.turn_on
      entity_id:  switch.smart_plug_one
    - delay:
        minutes: '15'
    - service: switch.turn_off
      entity_id:  switch.smart_plug_one

# Bathroom Lights off early morning with bedroom motion
- alias: Bathroom Lights off Bedroom Motion
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002047afe #LR Sensor
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '04:30:00'
        before: '06:00:00'
      - condition: state
        entity_id: input_boolean.bedtime_sean
        state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2
