
# Bathroom Lights on with Motion
- alias: Bathroom Lights on motion
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '07:00:01'
        before: '21:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'

# Bathroom Lights on with Motion at Bedtime
- alias: Bathroom Lights on motion bedtime
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '21:00:01'
        before: '04:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.ba4
        brightness_pct: '10'
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.ba4
        brightness_pct: '10'

# Bathroom Lights on with Motion at Early Morning
- alias: Bathroom Lights on motion early morning
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: light.bathroom
        state: 'off'
      - condition: time
        after: '04:00:01'
        before: '07:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
        transition: 60
    - delay:
        seconds: '1'
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
        transition: 60

# Bathroom Lights off without Motion night
- alias: Bathroom Lights off no motion night
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'off'
    for:
      seconds: 30
  condition:
    - condition: time
      after: '21:00:01'
      before: '04:20:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2

# Bathroom Lights off without Motion
- alias: Bathroom Lights off no motion
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 3
  condition:
    - condition: time
      after: '04:20:01'
      before: '21:00:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2

# Turn on air fresh for ten minutes each hour when home
- alias: Turn on air fresh
  trigger:
    platform: time
    hours: '/1'
    minutes: '00'
    seconds: '00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '06:00:00'
        before: '22:15:00'
  action:
    - service: switch.turn_on
      entity_id:  switch.smart_plug_one
    - delay:
        minutes: '10'
    - service: switch.turn_off
      entity_id:  switch.smart_plug_one
