# Auto Bedroom Brightness
- alias: Bedroom Auto Brightness
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.bedroom_motion
      to: 'on'
    - platform: state
      entity_id: group.closet_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.bedroom_occupied
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.bedroom
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime_sean
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_bedroom_tv', 'playing') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.plex_bedroom_tv', 'paused') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.bedroom_speaker', 'playing') }}" # NOT condition
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.bedroom
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - delay:
        milliseconds: 500
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.bedroom
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Auto Bedroom Brightness Transition
- alias: Bedroom Auto Brightness Transition
  initial_state: on
  trigger:
    - platform: state
      entity_id: sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_bedroom_tv', 'playing') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.plex_bedroom_tv', 'paused') }}" # NOT condition
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.bedroom
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: false
        transition: '60'
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Bedroom Lights off without Motion
- alias: Bedroom Lights off no motion
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: '/3'
  condition:
    - condition: state
      entity_id: input_boolean.sean_bedroom_presence
      state: 'off'
    - condition: state
      entity_id: input_boolean.emily_bedroom_presence
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedroom_occupied
      state: 'off'
    - condition: state
      entity_id: group.bedroom_motion
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('sensor.sean_room_location', 'bedroom') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('sensor.emily_room_location', 'bedroom') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('sensor.steam_76561198154412871', 'online') }}" # NOT condition
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom
        transition: 2
    - delay:
        milliseconds: 500
    - service: light.turn_off
      data:
        entity_id: light.bedroom
        transition: 2

# Closet lights
- alias: Closet Lights On
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.closet_motion
      to: 'on'
  condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.bedtime_emily
            state: 'off'
          - condition: state
            entity_id: input_boolean.bedtime_sean
            state: 'off'
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: switch.turn_on
      data_template:
        entity_id: switch.closet_light

# Closet Lights Off without Motion
- alias: Closet Lights off no motion
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: '/2'
  condition:
    - condition: state
      entity_id: group.closet_motion
      state: 'off'
      for:
        minutes: 2
  action:
    service: switch.turn_off
    data:
      entity_id: switch.closet_light

# Bedroom Lights off without Motion
#- alias: Bedroom Lights off no motion
#  initial_state: on
#  trigger:
#    platform: state
#    entity_id: binary_sensor.motion_sensor_158d000237a64a
#    to: 'off'
#    for:
#      minutes: 3
#  action:
#    service: light.turn_off
#    data:
#      entity_id: light.bedroom
#      transition: 2
