# Bedroom Lights on with Motion
- alias: Bedroom Lights on motion
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '08:00:00'
        before: '21:00:00'
      - condition: numeric_state
        entity_id: sensor.phone_socket
        below: '.1'
      - condition: template
        value_template: "{{ not is_state('media_player.bedroom_tv', 'playing') }}" # NOT condition
      - condition: template
        value_template: "{{ not is_state('media_player.bedroom_speaker', 'playing') }}" # NOT condition
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom
      brightness: '255'

# Bedroom Lights off without Motion
- alias: Bedroom Lights off no motion
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom
      transition: 2
