# Living Room Auto Brightness with Motion Detection
- alias: Living Room Auto Brightness
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        - group.living_room_motion
        - binary_sensor.humen_sensor_1m_91d78c_presence
        - binary_sensor.humen_sensor_1m_91d78c_moving_target
        - binary_sensor.humen_sensor_1m_91d9f0_moving_target
        - binary_sensor.humen_sensor_1m_91d9f0_presence
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'playing') and not is_state('media_player.plex_living_room_tv', 'paused') and not is_state('media_player.nvidia_shield_pro', 'playing') and not is_state('media_player.nvidia_shield_pro', 'paused') }}"
  action:
    - service: adaptive_lighting.apply
      data:
        lights: [light.living_room]
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        transition: 1
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
    - delay:
        milliseconds: 500
    - service: adaptive_lighting.apply
      data:
        lights: [light.living_room]
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        transition: 1
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400

# Living Room Brightness Transition (Sunset to Sunrise)
- alias: Living Room Auto Brightness Transition
  initial_state: on
  trigger:
    platform: state
    entity_id: 
      - sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'playing') and not is_state('media_player.plex_living_room_tv', 'paused') and not is_state('media_player.nvidia_shield_pro', 'playing') and not is_state('media_player.nvidia_shield_pro', 'paused') }}"
  action:
    - service: adaptive_lighting.apply
      data:
        lights: [light.living_room]
        adapt_brightness: true
        adapt_color: true
        transition: 60
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Living Room Lights off with No Motion
- alias: Living Room Lights Off Without Motion
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: '/3'
  condition:
    - condition: state
      entity_id:
        - input_boolean.sean_living_room_presence
        - input_boolean.emily_living_room_presence
        - input_boolean.living_room_occupied
        - group.living_room_motion
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'playing') and not is_state('media_player.plex_living_room_tv', 'paused') and not is_state('media_player.nvidia_shield_pro', 'playing') and not is_state('media_player.nvidia_shield_pro', 'paused') }}"
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights
        brightness_pct: 1
        kelvin: 5400
    - delay:
        milliseconds: 500
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2

# Living Room Lights Off at Bedtime (if Sean is Not Home)
- alias: Living Room Lights Off at Bedtime (Sean Not Home)
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.bedtime_emily
    to: 'on'
  condition:
    - condition: state
      entity_id: group.sean
      state: 'not_home'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
    - service: automation.turn_off
      entity_id: automation.living_room_auto_brightness

# Outside Lights On at Sunset
- alias: Outside Lights On at Sunset
  initial_state: on
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.outside_lights_switch
    - service: light.turn_on
      data:
        entity_id: light.signify_netherlands_b_v_lwb014_huelight_2
        brightness_pct: 60
        transition: 2

# Outside Lights Off at Sunrise
- alias: Outside Lights Off at Sunrise
  initial_state: on
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: automation.turn_on
      target:
        entity_id: automation.living_room_auto_brightness_transition
    - service: switch.turn_off
      entity_id: switch.outside_lights_switch
    - service: light.turn_off
      data:
        entity_id: light.signify_netherlands_b_v_lwb014_huelight_2
        transition: 2

# Randomize Hue Scenes at Sunset
- alias: Randomize Hue Scenes
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: '/7'
  condition:
    - condition: state
      entity_id: group.seanemily
      state: 'home'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: input_boolean.bedtime_sean
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: 'off'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: time
      after: '19:00:00'
      before: '17:00:00'
  action:
    - variables:
        options: "{{ state_attr('input_select.hue_scenes', 'options') }}"
        random_index: "{{ range(options | length) | random }}"
    - service: input_select.select_option
      data:
        option: "{{ options[random_index] }}"
      target:
        entity_id: input_select.hue_scenes
    - service: scene.turn_on
      data:
        entity_id: "{{ options[random_index] }}"
        transition: 90
    - service: automation.turn_off
      target:
        entity_id: automation.living_room_auto_brightness_transition

# Turn on Cabinet Lights if Watching TV
- alias: Joyce Cabinet Lights On
  initial_state: off
  trigger:
    - platform: time_pattern
      minutes: '/3'
    - platform: template
      value_template: "{{ states('sensor.joyce_room_location') in ['living_room', 'kitchen', 'sunroom'] }}"
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime_sean
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
        transition: 2
