# General Media Player Automations with Smart Delay for Idle/Unavailable State
- alias: "Media Player Automations"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - media_player.plex_living_room_tv
      from: 
        - "playing"
        - "paused"
        - "idle"
        - "unavailable"
      to:
        - "playing"
        - "paused"
        - "idle"
        - "unavailable"

  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"

  action:
    - choose:
        # ▶ **Media player is playing**
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'playing' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.living_room
                transition: 4
            - service: switch.turn_off
              entity_id: switch.christmas_tree
            - service: light.turn_on
              data:
                entity_id: light.cabinet_lights
                brightness_pct: 1
                kelvin: 5400

        # ⏸ **Media player is paused**
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'paused' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.living_room
                brightness_pct: 33
                transition: 4
            - service: light.turn_on
              data:
                entity_id: light.cabinet_lights
                brightness_pct: 100
                kelvin: 5400
                transition: 4
            - delay:
                seconds: 1
            - service: light.turn_on
              data:
                entity_id: light.living_room
                brightness_pct: 33
                transition: 4

        # ⏹ **Media player goes idle or unavailable (Smart Delay with State Re-Check)**
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state in ['idle', 'unavailable'] }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.cabinet_lights
                brightness_pct: 100
                kelvin: 5400
                transition: 6
            - service: adaptive_lighting.apply
              data:
                lights:
                  - light.living_room
                turn_on_lights: true
                transition: 10
                entity_id: switch.adaptive_lighting_adapt_brightness_default
            - service: switch.turn_on
              entity_id: switch.christmas_tree
