# Turn off cabinet lights if alone
- alias: Turn off Cabinet Lights
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: template
      value_template: "{{ not states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom','couch'] }}" # NOT condition
      for:
        minutes: 5
  condition:
    - condition: template
      value_template: "{{ is_state('media_player.plex_living_room_tv', 'playing') }}"
    - condition: template
      value_template: "{{ is_state('media_player.nvidia_shield_pro', 'playing') }}"
    - condition: template
      value_template: "{{ not states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom','couch'] }}" # NOT condition
    - condition: state
      entity_id: light.cabinet_lights
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_lights
        brightness_pct: 1
        kelvin: 5400

# Lights back to full after media stops
- alias: "Media player stopped"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "playing"
      to: "idle"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "playing"
      to: "idle"
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.living_room
        turn_on_lights: true
        transition: 15
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
        transition: 10
    - service: automation.turn_on
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Lights back to full after media stops
- alias: "Media player stopped unavailable"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "playing"
      to: "unavailable"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "playing"
      to: "unavailable"
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.living_room
        turn_on_lights: true
        transition: 10
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
        transition: 15

# Lights turn off while media is playing
- alias: "Media player playing"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      to: "playing"
      from: "idle"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      to: "playing"
      from: "idle"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom'] }}"
      then:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4
      else:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4
        - service: light.turn_on
          data_template:
            entity_id: light.cabinet_lights
            brightness_pct: 1
            kelvin: 5400


# Lights turn off while media is playing
- alias: "Media player playing unavailable"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      to: "playing"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      to: "playing"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom'] }}"
      then:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4
      else:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4
        - service: light.turn_on
          data_template:
            entity_id: light.cabinet_lights
            brightness_pct: 1
            kelvin: 5400

# Lights dim when media is paused
- alias: "Media player paused"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "playing"
      to: "paused"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "playing"
      to: "paused"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom'] }}"
      then:
        - service: light.turn_on
          data:
            entity_id: light.living_room
            brightness_pct: 33
            transition: 4
        - service: light.turn_on
          data_template:
            entity_id: light.cabinet_lights
            brightness_pct: 100
            kelvin: 5400
            transition: 4
        - delay:
            seconds: 1
        - service: light.turn_on
          data:
            entity_id: light.living_room
            brightness_pct: 33
            transition: 4
      else:
        - service: light.turn_on
          data:
            entity_id: light.living_room
            brightness_pct: 33
            transition: 4
        - service: light.turn_on
          data_template:
            entity_id: light.cabinet_lights
            brightness_pct: 50
            kelvin: 5400
            transition: 4
        - delay:
            seconds: 1
        - service: light.turn_on
          data:
            entity_id: light.living_room
            brightness_pct: 33
            transition: 4

# Lights turn off when media is unpaused
- alias: "Media player unpaused"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "paused"
      to: "playing"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "paused"
      to: "playing"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom'] }}"
      then:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4
        - service: light.turn_on
          data_template:
            entity_id: light.cabinet_lights
            brightness_pct: 1
            kelvin: 5400
      else:
        - service: light.turn_off
          data:
            entity_id: light.living_room
            transition: 4

# Lights dim to full going from paused to idle
- alias: "Media player pause to idle"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "paused"
      to: "idle"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "paused"
      to: "idle"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.living_room
        adapt_brightness: true
        adapt_color: false
        turn_on_lights: true
        transition: 5
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
        transition: 6

# Lights dim to full going from paused to idle
- alias: "Media player pause to unavailable"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: "paused"
      to: "unavailable"
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_bravia_vh1
      from: "paused"
      to: "unavailable"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.nvidia_shield_pro
          attribute: source
          state: "Spotify"
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.living_room
        adapt_brightness: true
        adapt_color: false
        turn_on_lights: true
        transition: 5
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - service: light.turn_on
      data_template:
        entity_id: light.cabinet_lights
        brightness_pct: 100
        kelvin: 5400
        transition: 6
