- alias: "Bedroom media player automation"
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        - media_player.plex_bedroom_stick
  condition: []
  action:
    - choose:
        # Lights back to full over 7 seconds after media stops
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'playing' and trigger.to_state.state == 'idle' }}"
            - condition: state
              entity_id: input_boolean.bedtime_emily
              state: "off"
          sequence:
            - service: adaptive_lighting.apply
              data:
                lights:
                  - light.bedroom
                adapt_brightness: true
                adapt_color: false
                turn_on_lights: true
                transition: 15
                entity_id: switch.adaptive_lighting_adapt_brightness_default

        # Lights turn off while media is playing
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'playing' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.bedroom
                transition: 4

        # Lights dim when media is paused
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'playing' and trigger.to_state.state == 'paused' }}"
            - condition: state
              entity_id: input_boolean.bedtime_emily
              state: "off"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.bedroom
                brightness_pct: 33
                transition: 7

        # Lights turn off when media is unpaused
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'paused' and trigger.to_state.state == 'playing' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.bedroom

        # Lights dim to full going from paused to idle
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'paused' and trigger.to_state.state == 'idle' }}"
            - condition: state
              entity_id: input_boolean.bedtime_emily
              state: "off"
          sequence:
            - service: adaptive_lighting.apply
              data:
                lights:
                  - light.bedroom
                adapt_brightness: true
                adapt_color: false
                turn_on_lights: true
                transition: 10
                entity_id: switch.adaptive_lighting_adapt_brightness_default
      default: []
