# Bedroom Media Player Automation with Smart Idle Delay
- alias: "Bedroom media player automation"
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        - media_player.plex_bedroom_stick
  
  action:
    - choose:
        # ▶ **Lights turn off when media is playing**
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'playing' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.bedroom
                transition: 4

        # ⏸ **Lights dim when media is paused**
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'playing' and trigger.to_state.state == 'paused' }}"
            - condition: state
              entity_id: input_boolean.bedtime_emily
              state: "off"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.bedroom
                brightness_pct: 33
                transition: 7

        # ▶ **Lights turn off when media is unpaused**
        - conditions:
            - condition: template
              value_template: "{{ trigger.from_state.state == 'paused' and trigger.to_state.state == 'playing' }}"
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.bedroom

        # ⏹ **Smart Delay Before Lights Change on Idle**
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state in ['idle', 'unavailable'] }}"
            - condition: state
              entity_id: input_boolean.bedtime_emily
              state: "off"
          sequence:
            - service: adaptive_lighting.apply
              data:
                lights:
                  - light.bedroom
                turn_on_lights: true
                transition: 10
                entity_id: switch.adaptive_lighting_adapt_brightness_default
