# Auto Office Brightness
- alias: "Office Auto Brightness"
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.office_motion
      to: "on"
    - platform: state
      entity_id: input_boolean.office_occupied
      to: "on"
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    #- service: switch.turn_on
    #  data:
    #    entity_id: switch.wake_on_lan
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        entity_id: switch.adaptive_lighting_adapt_brightness_default
    - delay:
        milliseconds: 500
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Auto Office Brightness Transition
- alias: "Office Auto Brightness Transition"
  initial_state: on
  trigger:
    - platform: state
      entity_id: sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: light.silicon_labs_ezsp_office_lights_zha_group_0x0002
      state: "on"
  action:
    - service: adaptive_lighting.apply
      data:
        lights:
          - light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        adapt_brightness: true
        adapt_color: true
        turn_on_lights: true
        transition: 60
        entity_id: switch.adaptive_lighting_adapt_brightness_default

# Turn off Office Lights after one minute of no activity
- alias: "Turn office lights without motion one min"
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: "/3"
  condition:
    - condition: state
      entity_id: input_boolean.sean_office_presence
      state: "off"
    - condition: state
      entity_id: input_boolean.emily_office_presence
      state: "off"
    - condition: state
      entity_id: group.office_motion
      state: "off"
    - condition: state
      entity_id: input_boolean.office_occupied
      state: "off"
    - condition: template
      value_template: "{{ not is_state('sensor.steam_76561197976250572', 'online') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('sensor.sean_room_location', 'office') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('sensor.emily_room_location', 'office') }}" # NOT condition
  action:
    - service: light.turn_off
      data:
        entity_id: light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        transition: 2
    - delay:
        milliseconds: 250
    - service: light.turn_off
      data:
        entity_id: light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        transition: 2

# Auto Office Brightness
- alias: Steam dim office lights
  initial_state: off
  trigger:
    - platform: state
      entity_id: sensor.steam_76561197976250572
      attribute: game
      to:
  condition:
    - condition: state
      entity_id: light.silicon_labs_ezsp_office_lights_zha_group_0x0002
      state: "on"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.silicon_labs_ezsp_office_lights_zha_group_0x0002
        brightness_pct: 20
        transition: 10