# ✅ Turn on Office Fan Based on Motion & Temperature
- alias: "Turn on Office Fan on Motion or Temperature"
  initial_state: on
  trigger:
    # Motion detected in the office
    - platform: state
      entity_id: group.office_motion
      to: "on"

    # Temperature goes above 72°F
    - platform: numeric_state
      entity_id: sensor.office_temperature_f
      above: 72

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.sean_green
        state: "home"
      - condition: numeric_state
        entity_id: sensor.office_temperature_f
        above: 72
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.office_occupied
            state: "on"
          - condition: state
            entity_id: group.office_motion
            state: "on"

  action:
    - service: switch.turn_on
      entity_id: switch.office_fan

# ✅ Turn off Office Fan When Room Cools or Becomes Unoccupied
- alias: "Turn off Office Fan When Temp Drops or Room Empty"
  initial_state: on
  trigger:
    # Temperature drops below 71°F
    - platform: numeric_state
      entity_id: sensor.office_temperature_f
      below: 71

    # Office occupancy turns off for 10 minutes
    - platform: state
      entity_id: input_boolean.office_occupied
      to: "off"
      for:
        minutes: 10

  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('sensor.steam_76561197976250572', 'online') }}" # Ensures Steam status doesn't override shutdown
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.office_temperature_f
            below: 71
          - condition: state
            entity_id: input_boolean.office_occupied
            state: "off"

  action:
    - service: switch.turn_off
      entity_id: switch.office_fan
