## OFFICE ##
- alias: Office occupied
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.office_motion
      to: "on"
    - platform: template
      value_template: "{{ states('sensor.sean_room_location') in ['office','guest'] }}"
      for:
        seconds: 5
    - platform: template
      value_template: "{{ states('sensor.emily_room_location') in ['office','guest'] }}"
      for:
        seconds: 5
    - platform: state
      entity_id: sensor.steam_76561197976250572
      to: "online"
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.office_occupied

- alias: Office unoccupied
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ not states('sensor.sean_room_location') in ['office','guest'] }}" # NOT condition
      for:
        minutes: 6
    - platform: template
      value_template: "{{ not states('sensor.emily_room_location') in ['office','guest'] }}" # NOT condition
      for:
        minutes: 6
    - platform: time_pattern
      minutes: "/7"
  condition:
    condition: and
    conditions:
#      - condition: state
#        entity_id: binary_sensor.office_unoccupied
#        state: "on"
      - condition: state
        entity_id: group.office_motion
        state: "off"
      - condition: template
        value_template: "{{ not states('sensor.sean_room_location') in ['office','guest'] }}" # NOT condition
      - condition: template
        value_template: "{{ not states('sensor.emily_room_location') in ['office','guest'] }}" # NOT condition
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.office_occupied

- alias: Sean Office Location
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.sean_room_location
      to: "office"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Office

- alias: Emily Office Location
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.emily_room_location
      to: "office"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.emily_room_location
        option: Office

## LIVING ROOM ##
- alias: Living Room occupied
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.living_room_motion
      to: "on"
    - platform: template
      value_template: "{{ states('sensor.sean_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}"
      for:
        seconds: 10
    - platform: template
      value_template: "{{ states('sensor.emily_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}"
      for:
        seconds: 10
    - platform: template
      value_template: "{{ states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}"
      for:
        seconds: 10
  #      - platform: template
  #        value_template: "{{ not is_state('media_player.plex_living_room_tv', 'unavailable') }}" # NOT condition
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_occupied

# Only when one person is home.
- alias: Living Room unoccupied
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ not states('sensor.sean_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
      for:
        minutes: 3
    - platform: template
      value_template: "{{ not states('sensor.emily_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
      for:
        minutes: 3
    - platform: template
      value_template: "{{ not states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
      for:
        minutes: 3
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: and
    conditions:
#      - condition: state
#        entity_id: binary_sensor.living_room_unoccupied
#        state: "on"
      - condition: state
        entity_id: group.living_room_motion
        state: "off"
      - condition: template
        value_template: "{{ not states('sensor.sean_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
      - condition: template
        value_template: "{{ not states('sensor.emily_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
      - condition: template
        value_template: "{{ not states('sensor.joyce_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}" # NOT condition
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.living_room_occupied

- alias: Sean Living Room Location
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states('sensor.sean_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Living Room

- alias: Emily Living Room Location
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states('sensor.emily_room_location') in ['living_room','kitchen','sunroom','couch','foyer'] }}"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.emily_room_location
        option: Living Room

## BEDROOM ##
- alias: Bedroom occupied
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.bedroom_motion
      to: "on"
    - platform: template
      value_template: "{{ states('sensor.sean_room_location') in ['bedroom','bedroom2'] }}"
      for:
        seconds: 10
    - platform: template
      value_template: "{{ states('sensor.emily_room_location') in ['bedroom','bedroom2'] }}"
      for:
        seconds: 10
    - platform: state
      entity_id: input_boolean.sean_bedtime
      to: "on"
    - platform: state
      entity_id: input_boolean.emily_bedtime
      to: "on"
    - platform: template
      value_template: "{{ not is_state('media_player.bedroom_tv', 'unavailable') }}" # NOT condition
    - platform: template
      value_template: "{{ not is_state('media_player.bedroom_tv', 'idle') }}" # NOT condition
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedroom_occupied

- alias: Bedroom unoccupied
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ not states('sensor.sean_room_location') in ['bedroom','bedroom2'] }}" # NOT condition
      for:
        minutes: 3
    - platform: template
      value_template: "{{ not states('sensor.emily_room_location') in ['bedroom','bedroom2'] }}" # NOT condition
      for:
        minutes: 3
    - platform: time_pattern
      minutes: "/5"
  condition:
#    - condition: state
#      entity_id: binary_sensor.bedroom_unoccupied
#      state: "on"
    - condition: state
      entity_id: group.bedroom_motion
      state: "off"
    - condition: template
      value_template: "{{ not states('sensor.sean_room_location') in ['bedroom','bedroom2'] }}" # NOT condition
    - condition: template
      value_template: "{{ not states('sensor.emily_room_location') in ['bedroom','bedroom2'] }}" # NOT condition
    - condition: template
      value_template: "{{ not states('sensor.joyce_room_location') in ['bedroom','bedroom2'] }}" # NOT condition
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.bedroom_occupied

- alias: Sean Bedroom Location
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states('sensor.sean_room_location') in ['bedroom','bedroom2'] }}"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Bedroom

- alias: Emily Bedroom Location
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states('sensor.emily_room_location') in ['bedroom','bedroom2'] }}"
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.emily_room_location
        option: Bedroom

# Emily is now home and location is unknown
- alias: "Emily is Home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: person.emily_green
      to: "home"
    - platform: state
      entity_id: sensor.emily_room_location
      to: not_home
      for:
        minutes: 1
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.emily_room_location
        option: Home

# Emily is away from the house
- alias: "Emily is Away"
  initial_state: on
  trigger:
    - platform: state
      entity_id: person.emily_green
      to: "not_home"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.emily_room_location
        option: Away

# Sean is now home and location is unknown
- alias: "Sean is Home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: person.sean_green
      to: "home"
    - platform: state
      entity_id: sensor.sean_room_location
      to: not_home
      for:
        minutes: 1
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Home

# Sean is away from the house
- alias: "Sean is Away"
  initial_state: on
  trigger:
    - platform: state
      entity_id: person.sean_green
      to: "not_home"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Away
