# Sean is in the living Room using Google Home BT tracking
- alias: Sean in Living Room
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.livingroom_sean_gh_rssi
    - platform: state
      entity_id: sensor.office_sean_gh_rssi
    - platform: state
      entity_id: sensor.bedroom_sean_gh_rssi
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ ( states.sensor.office_sean_gh_rssi.state ) > ( states.sensor.livingroom_sean_gh_rssi.state ) }}"
        - condition: template
          value_template: "{{ ( states.sensor.bedroom_sean_gh_rssi.state ) > ( states.sensor.livingroom_sean_gh_rssi.state ) }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sean_living_room_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_bedroom_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_office_presence
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Living Room

# Sean is in the Office using Google Home BT tracking
- alias: Sean in Office
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.livingroom_sean_gh_rssi
    - platform: state
      entity_id: sensor.office_sean_gh_rssi
    - platform: state
      entity_id: sensor.bedroom_sean_gh_rssi
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ ( states.sensor.livingroom_sean_gh_rssi.state ) > ( states.sensor.office_sean_gh_rssi.state  ) }}"
        - condition: template
          value_template: "{{ ( states.sensor.bedroom_sean_gh_rssi.state ) > ( states.sensor.office_sean_gh_rssi.state ) }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_living_room_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_bedroom_presence
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sean_office_presence
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Office

# Sean is in the bedroom using Google Home BT tracking
- alias: Sean in Bedroom
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.livingroom_sean_gh_rssi
    - platform: state
      entity_id: sensor.office_sean_gh_rssi
    - platform: state
      entity_id: sensor.bedroom_sean_gh_rssi
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ ( states.sensor.livingroom_sean_gh_rssi.state ) > ( states.sensor.bedroom_sean_gh_rssi.state ) }}"
        - condition: template
          value_template: "{{ ( states.sensor.office_sean_gh_rssi.state ) > ( states.sensor.bedroom_sean_gh_rssi.state ) }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_living_room_presence
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sean_bedroom_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_office_presence
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Bedroom

# Sean is away from the house
- alias: 'Sean is Away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.sean_phone
      to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Away
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_living_room_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_bedroom_presence
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sean_office_presence

# Sean is now home and BT is unknown
- alias: 'Sean is Home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.sean_phone
      to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sean_room_location
        option: Home
